-- Q1: Calculate total revenue generated by the business
-- Business Insight:
-- Helps understand overall business size and performance
SELECT
    ROUND(SUM(oi.quantity * oi.price), 2) AS total_revenue
FROM order_items oi;
-- =============================================================================================================================================

-- Q2: Count number of orders placed by each customer
-- Business Insight:
-- Identifies active vs inactive customers
SELECT
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_orders DESC;
-- =============================================================================================================================================

-- Q3: Calculate revenue generated by each product category
-- Business Insight:
-- Shows which product categories drive the most revenue
SELECT
    p.category,
    ROUND(SUM(oi.quantity * oi.price), 2) AS category_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY category_revenue DESC;
-- =============================================================================================================================================

-- Q4: Count number of customers in each region
-- Business Insight:
-- Helps in regional targeting and expansion planning
SELECT
    region,
    COUNT(customer_id) AS customer_count
FROM customers
GROUP BY region
ORDER BY customer_count DESC;
-- =============================================================================================================================================

-- Q5: Calculate average order value
-- Business Insight:
-- Measures how much revenue is generated per order on average

WITH order_values AS (
    SELECT
        o.order_id,
        SUM(oi.quantity * oi.price) AS order_revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.order_id
)

SELECT
    ROUND(AVG(order_revenue), 2) AS average_order_value
FROM order_values;
-- =============================================================================================================================================



